### PR TITLE
Fix EmailField / URLField required=False

### PR DESCRIPTION
**Pull request by berycz**
fix for #423

### CODE REVIEW

**Comment by berycz** [comment]
hmm, I'm not sure whether to fix the tests or set default `field=None`?

**Comment by jlubcke** [comment]
It would be nice with some test cases showing the different cases.

**Comment by boxed** [comment]
The existing code has `return <something> or string_value` but the `or` can never apply since `<something>` raises....

**Comment by berycz** [comment]
yea, I was also thinking what's the point of ` or string_value` :)
and I was also thinking if instead of `field=None` there shouldnt be rather something like `allow_empty=False` with `self.invoke_callback(self.parse, string_value=raw_data, allow_empty=not field.required)` on L870?

**Comment by berycz** [comment]
oh I got the `or string_value`
validators either raise exception or return "nothing" (None)
so if the email/url is valid, then it's `return None or string_value`

**Comment by boxed** [comment]
Thanks!

**Pull request merged**
