### PR TITLE
removing preserved page, to always jump to the first page after filtering

### PR DESCRIPTION
**Pull request by berycz**

### CODE REVIEW

**Comment by boxed** [comment]
@jlubcke should we be using some version of invoke_callback or something here?

**Comment by boxed** [comment]
Cool. I'll merge then.

**Comment by jlubcke** [comment]
:) I will dig a bit more to see if I can come up with something prettier.

**Comment by boxed** [comment]
I figured there was something a little cleaner :P

**Comment by jlubcke** [comment]
I made a followup in #501

**Comment by boxed** [comment]
Heh, yea that kind of cleanup was more in line with what I expected you'd pull out of your hat :P

**Pull request merged**
